[build]
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Form settings
[forms]
  settings = "forms/"

# Redirect rules
[[redirects]]
  from = "/contact-form.html"
  to = "/"
  status = 301